userContent = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(userContent))
print('Só tem espaços? ', userContent.isspace())
print('É um número? ', userContent.isnumeric())
print('É alfabético? ', userContent.isalpha())
print('É alfanumérico? ', userContent.isalnum())
print('Está maiúsculo? ', userContent.isupper())
print('Está em minúsculo?', userContent.islower())
print('Está capitalizada?', userContent.istitle())